// export const CREATE_BLOG = "CREATE_BLOG";
// export const EDIT_BLOG = "EDIT_BLOG";
// export const LIKE_BLOG = "LIKE_BLOG";
// export const UNLIKE_BLOG = "UNLIKE_BLOG";
// export const COMMENT_BLOG = "COMMENT_BLOG";
// export const EDIT_COMMENT_BLOG = "EDIT_COMMENT_BLOG";
// export const DELETE_COMMENT_BLOG = "DELETE_COMMENT_BLOG";

export const SIGN_IN = "SIGN_IN";
export const SIGN_OUT = "SIGN_OUT";
export const LOAD_USER_BLOGS_SUCCESS = "LOAD_USER_BLOGS_SUCCESS";

export const CREATE_BLOG = "CREATE_BLOG";

export const LOAD_ALL_BLOGS_SUCCESS = "LOAD_ALL_BLOGS_SUCCESS";
export const LOAD_TECHNOLOGY_BLOGS_SUCCESS = "LOAD_TECHNOLOGY_BLOGS_SUCCESS";
export const LOAD_CAD_BLOGS_SUCCESS = "LOAD_CAD_BLOGS_SUCCESS";
export const LOAD_ONCALL_BLOGS_SUCCESS = "LOAD_ONCALL_BLOGS_SUCCESS";
export const LOAD_XALT_BLOGS_SUCCESS = "LOAD_XALT_BLOGS_SUCCESS";